# APP_NAME=Laravel
# APP_ENV=local
# APP_KEY=base64:L52FVmv2f8N4VIatk05NIsVA06F0PsFq84k2tR19WVw=
# APP_DEBUG=true
# APP_URL=http://tms.test

# LOG_CHANNEL=stack
# LOG_DEPRECATIONS_CHANNEL=null
# LOG_LEVEL=debug

# DB_CONNECTION=mysql
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=tms
# DB_USERNAME=homestead
# DB_PASSWORD=secret

# BROADCAST_DRIVER=log
# CACHE_DRIVER=file
# FILESYSTEM_DRIVER=local
# QUEUE_CONNECTION=sync
# SESSION_DRIVER=file
# SESSION_LIFETIME=120

# MEMCACHED_HOST=127.0.0.1

# REDIS_HOST=127.0.0.1
# REDIS_PASSWORD=null
# REDIS_PORT=6379

# MAIL_MAILER=smtp
# MAIL_HOST=mailhog
# MAIL_PORT=1025
# MAIL_USERNAME=null
# MAIL_PASSWORD=null
# MAIL_ENCRYPTION=null
# MAIL_FROM_ADDRESS=null
# MAIL_FROM_NAME="${APP_NAME}"

# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_DEFAULT_REGION=us-east-1
# AWS_BUCKET=
# AWS_USE_PATH_STYLE_ENDPOINT=false

# PUSHER_APP_ID=
# PUSHER_APP_KEY=
# PUSHER_APP_SECRET=
# PUSHER_APP_CLUSTER=mt1

# MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
# MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
# FIREBASE_PROJECT=laraveltms
# FIREBASE_CREDENTIALS=resources/credentials/firebase_credentials.json
# FIREBASE_DATABASE_URL=https://laraveltms-b022f-default-rtdb.firebaseio.com/

env_variables:
  APP_NAME: "tms-laravel"
  APP_ENV: "production"
  APP_KEY: "base64:L52FVmv2f8N4VIatk05NIsVA06F0PsFq84k2tR19WVw="
  APP_DEBUG: false
  SESSION_LIFETIME: 1440
  PORT: 8080
  # DB_CONNECTION: mysql
  # DB_HOST: 34.66.138.155
  # DB_PORT: 3306
  # DB_DATABASE: tms_cloud
  # DB_USERNAME: root
  # DB_PASSWORD: A7med1234

  # MAIL_MAILER=smtp
  # MAIL_HOST=mailhog
  # MAIL_PORT=1025
  # MAIL_USERNAME=null
  # MAIL_PASSWORD=null
  # MAIL_ENCRYPTION=null
  # MAIL_FROM_ADDRESS=null
  # MAIL_FROM_NAME="${APP_NAME}"

  FIREBASE_PROJECT_ID: "laraveltms-b022f"
  FIREBASE_APP_ID: "1:535725536461:web:e876f3f0aaec6af738e584"
  FIREBASE_AUTH_DOMAIN: "laraveltms-b022f.firebaseapp.com"
  FIREBASE_DATABASE_URL: "https://laraveltms-b022f-default-rtdb.firebaseio.com/"
  FIREBASE_STORAGE_BUCKET: "laraveltms-b022f.appspot.com"
  FIREBASE_CREDENTIALS: "resources/credentials/firebase_credentials.json"